### ISSUE TITLE
(macOS 13.4.1 [Intel]) Broken Spotify Link Button

### ISSUE THREAD

**Issue by miskeeping** [ezytdl/ezytdl#12]
### Title: 
Internal error occurred!

### Content: 
{}

TypeError: Cannot read properties of undefined (reading 'buttons')
    at callback (/Applications/ezytdl-nightly.app/Contents/Resources/app.asar/core/createDialog.js:21:39)
    at BrowserWindow.<anonymous> (/Applications/ezytdl-nightly.app/Contents/Resources/app.asar/core/createDialog.js:68:51)
    at BrowserWindow.emit (node:events:513:28)

(no stack)

### Stack: 
```js
- at module.exports (/Applications/ezytdl-nightly.app/Contents/Resources/app.asar/core/sendNotification.js:9:30)
- at module.exports (/Applications/ezytdl-nightly.app/Contents/Resources/app.asar/util/errorHandler.js:8:48)
- at process.<anonymous> (/Applications/ezytdl-nightly.app/Contents/Resources/app.asar/index.js:19:124)
- at process.emit (node:events:525:35)
- at process._fatalException (node:internal/process/execution:149:25)
```

### Below this line, please describe what caused this error.
----
Clicking "Link" on the Spotify section results in a blank window, causing error when closed

**Comment by sylviiu** [comment]
i can confirm the blank window is an issue for macOS (and linux, additionally) -- but i could not reproduce this particular error (unrelated maybe?)

![image](https://github.com/ezytdl/ezytdl/assets/95180094/60ff8b13-336b-4da0-83b9-d2416f6a70c4)

looking into both now
